.\"	$Header: /usr/people/sam/flexkit/fax/man/man1/RCS/dit2fax.1,v 1.1 91/05/08 17:38:08 sam Exp $
.\"
.\" Copyright (c) 1991 by Sam Leffler.
.\" All rights reserved.
.\"
.\" This file is provided for unrestricted use provided that this
.\" legend is included on all tape media and as a part of the
.\" software program in whole or part.  Users may copy, modify or
.\" distribute this file at will.
.\"
.TH DIT2FAX 1 "April 29, 1991"
.SH NAME
dit2fax \- convert 
.SM TROFF
output to PostScript for facsimile transmission
.SH SYNOPSIS
.B dit2fax
[
.B \-lm
]
.B \-o
.I output-file
.IR files ...
.SH DESCRIPTION
.I Dit2fax
is a program that is automatically invoked by
.IR sendfax (1)
to convert
.IR troff (1)
output
to PostScript; in preparation for sending a facsimile.
The specified files are concatentated and converted,
with the result placed in the file specified with the
.B \-o
option.
The
.B \-l
and
.B \-m
options indicate low (98 lpi) and medium (196 lpi)
resolution output is desired.
By default low resolution output should be produced.
.RB ( NB:
since PostScript is resolution independent, these flags are ignored.)
.PP
The default version of this script uses the
.I psdit
utility from Adobe's
.I Transcript
product\- it is assumed to be already installed on the system.
.SH BUGS
This program should be called
.IR dit2ps .
.SH "SEE ALSO"
.IR sendfax (1)
