.\"	$Header: /usr/people/sam/flexkit/fax/man/man1/RCS/text2fax.1,v 1.1 91/05/08 17:39:12 sam Exp $
.\"
.\" Copyright (c) 1991 by Sam Leffler.
.\" All rights reserved.
.\"
.\" This file is provided for unrestricted use provided that this
.\" legend is included on all tape media and as a part of the
.\" software program in whole or part.  Users may copy, modify or
.\" distribute this file at will.
.\"
.TH TEXT2FAX 1 "April 29, 1991"
.SH NAME
text2fax \- covert text to PostScript\(tm for facsimile transmission
.SH SYNOPSIS
.B text2fax
[
.B \-lm
]
.B \-o
.I output-file
.IR files ...
.SH DESCRIPTION
.I Text2fax
is a program that is automatically invoked by
.IR sendfax (1)
to convert 
.SM ASCII-\c
text to PostScript; in preparation for sending a facsimile.
The concatentation of the specified files is converted,
with the result placed in the file specified with the
.B \-o
option.
The
.B \-l
and
.B \-m
options indicate low (98 lpi) and medium (196 lpi)
resolution output is desired.
By default low resolution output should be produced.
(NB: since PostScript is usually resolution independent,
these flags are often ignored.)
.PP
The default version of this script uses the
.I enscript
utility from Adobe's
.I Transcript
product\- it is assumed to be already installed on the system.
.SH BUGS
This program should be called
.IR text2ps .
.SH "SEE ALSO"
.IR sendfax (1),
.IR dit2fax (1),
.IR sgi2fax (1),
.IR flexfax (4F)
